# Generated by Django 6.0 on 2025-12-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationpolicy',
            name='scopes',
            field=models.ManyToManyField(blank=True, to='identity.scope'),
        ),
        migrations.AlterField(
            model_name='applicationpolicy',
            name='session_timeout_seconds',
            field=models.IntegerField(default=1800),
        ),
    ]
