# Generated by Django 6.0 on 2025-12-16 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_applicationpolicy_scopes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolescope',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rolescope',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='role_scopes', to='identity.application'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rolescope',
            unique_together={('role', 'scope', 'application')},
        ),
    ]
