# Generated by Django 6.0 on 2025-12-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_alter_rolescope_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationpolicy',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='applicationpolicy',
            name='role',
        ),
        migrations.RemoveField(
            model_name='applicationpolicy',
            name='scopes',
        ),
    ]
