# Generated by Django 6.0 on 2026-03-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_user_contact_number_user_department_user_join_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Ella', max_length=120),
            preserve_default=False,
        ),
    ]
